version: '2'

services:
  prod:
    container_name: apimytexter_prod
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 9000:9000
    command: npm run start:dev

  #MySQL
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: mytexter
      MYSQL_USER: mytexter
      MYSQL_ROOT_PASSWORD: ZVjS2YQaL6L1
      MYSQL_PASSWORD: An0thrS3crt

    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
