version: '3.5'

services:
  api:
    container_name: apimytexter_dev
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8000:8000
    networks:
      - net

    command: npm run start:dev

  #MySQL
  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: mytexter
      MYSQL_USER: mytexter
      MYSQL_ROOT_PASSWORD: ZVjS2YQaL6L1
      MYSQL_PASSWORD: An0thrS3crt

    ports:
      - '3306:3306'
    networks:
      - net
    volumes:
      - dbdata:/var/lib/mysql

networks:
  net:
    driver: bridge

volumes:
  dbdata:
