version: '3.8'

services:
  dev:
    container_name: apimytexter_dev
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8000:8000
    command: npm run start:dev

  prod:
    container_name: apimytexter_prod
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 9000:9000
    command: npm run start
